# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Docker
# Build a Docker image
trigger:
- none
pool:
  vmImage: ubuntu-latest
variables:
  imageName: 'llteodoro/ansible'
  imageVersion: '1.0'
  dockerFile: 'Dockerfile_ansible'
  tag: '$(Build.BuildId)'
steps:
- script: |
    docker build -f $(dockerFile) -t $(imageName):$(imageVersion) .
    docker images
    docker login -u llteodoro -p $(DOCKERHUB_TOKEN)
    docker push $(imageName):$(imageVersion)